- name: configure INI for ODBC in /etc/odbcinst.ini
  ini_file:
    dest: "/etc/odbcinst.ini"
    section: "MariaDB"
    create: true
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
    - { option: "Description", value: "ODBC for MariaDB"}
    - { option: "Driver", value:  "{{ odbc_install_prefix }}/lib64/libmaodbc.so" }
    - { option: "Setup", value:  "{{ odbc_install_prefix }}/lib64/libmaodbc.so" }
    - { option: "FileUsage", value: "1" }

- name: configure INI for ODBC in /etc/odbc.ini
  ini_file:
    dest: "/etc/odbc.ini"
    section: "MySQL-{{ asterisk_cdrdb_name }}"
    create: true
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
    - { option: "Description", value: "MySQL connection to {{ asterisk_cdrdb_name }} database" }
    - { option: "Driver", value: "MariaDB" }
    - { option: "Server", value: "{{ mysql_host }}" }
    - { option: "Database", value: "{{ asterisk_cdrdb_name }}" }
    - { option: "Port", value: "3306" }
    - { option: "Socket", value: "{{ mysql_socket }}" }
    - { option: "option", value: "3" }