- name: Remove existing install source dir
  file: "path={{ install_odbc_srcdir }} state=absent"

- name: Create install source dir
  file: "path={{ install_odbc_srcdir }} state=directory"

- name: Clone MariaDB odbc connector src
  git: 
    repo: "{{ install_odbc_url }}"
    dest: "{{ install_odbc_srcdir }}"
    version: "{{ install_odbc_version }}"

- name: Build MariaDB odbc connector from source
  command: "{{ item }} chdir={{ install_odbc_srcdir }}"
  with_items:
    - cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DWITH_OPENSSL=true -DCMAKE_INSTALL_PREFIX={{ install_odbc_prefix }} -LH
    - make
    - make install
