- name: Remove existing install source dir
  file: "path={{ asterisk_srcdir }} state=absent"

- name: Create install source dir
  file: "path={{ asterisk_srcdir }} state=directory"

- name: Download and extract Asterisk source
  unarchive: "src={{ asterisk_url }} dest={{ asterisk_srcdir }} remote_src=yes extra_opts=--strip-components=1"

- name: Build Asterisk from tarball
  command: "{{ item }} chdir={{ asterisk_srcdir }}"
  with_items:
    - contrib/scripts/get_mp3_source.sh
    - ./configure --with-pjproject-bundled
    - make menuselect.makeopts
    - sed -i -e 's/^MENUSELECT_ADDONS=.*$/MENUSELECT_ADDONS=chan_mobile chan_ooh323 res_config_mysql app_mysql cdr_mysql/' menuselect.makeopts
    - sed -i -e 's/^MENUSELECT_APPS=.*$/MENUSELECT_APPS=app_flash app_skel app_dahdiras app_fax app_ivrdemo app_jack app_meetme app_osplookup app_setcallerid/' menuselect.makeopts
    - sed -i -e 's/^MENUSELECT_CORE_SOUNDS=.*$/MENUSELECT_CORE_SOUNDS=CORE-SOUNDS-EN-WAV CORE-SOUNDS-EN-ULAW CORE-SOUNDS-EN-ALAW CORE-SOUNDS-EN-GSM CORE-SOUNDS-EN-G729 CORE-SOUNDS-RU-WAV CORE-SOUNDS-RU-ULAW CORE-SOUNDS-RU-ALAW CORE-SOUNDS-RU-GSM CORE-SOUNDS-RU-G729/' menuselect.makeopts
    - sed -i -e 's/^MENUSELECT_MOH=.*$/MENUSELECT_MOH=MOH-OPSOUND-WAV MOH-OPSOUND-ULAW MOH-OPSOUND-ALAW MOH-OPSOUND-GSM MOH-OPSOUND-G729/' menuselect.makeopts
    - sed -i -e 's/^MENUSELECT_EXTRA_SOUNDS=.*$/MENUSELECT_EXTRA_SOUNDS=EXTRA-SOUNDS-EN-WAV/' menuselect.makeopts
    - make -j2
    - make uninstall-all
    - make install
    - make config
    - ldconfig

- name: Disable asterisk start at boot
  service:
    name: asterisk
    enabled: no