---
- name: Install required packages
  apt:
    name:
      - curl
      - policykit-1
      - xmlstarlet
      - libmariadbclient-dev
      - apt-transport-https
      - net-tools
      - build-essential
      - mariadb-client
      - bison
      - flex
      - apache2
      - curl
      - sox
      - libncurses5-dev
      - libssl-dev
      - lame
      - ffmpeg
      - mpg123
      - libxml2-dev
      - libnewt-dev
      - sqlite3
      - libsqlite3-dev
      - pkg-config
      - automake
      - libtool
      - autoconf
      - git
      - unixodbc-dev
      - uuid
      - uuid-dev
      - libasound2-dev
      - libogg-dev
      - libvorbis-dev
      - libicu-dev
      - libcurl4-openssl-dev
      - libical-dev
      - libneon27-dev
      - libsrtp2-dev
      - libspandsp-dev
      - sudo
      - subversion
      - libtool-bin
      - python-dev
      - unixodbc
      - dirmngr
      - sendmail-bin
      - sendmail
      - cmake
      - cron
      - sudo
      - wget
      - curl
      - libmariadb-dev
      - python-mysqldb
      - libedit-dev
      - libgmime-3.0-dev
      - portaudio19-dev
      - libiksemel-dev
    state: present

- name: Install MariaDB Server
  apt:
    name:
      - mariadb-server
  when: mysql_install

- name: Add PHP5.6 repo Key
  apt_key: url="https://packages.sury.org/php/apt.gpg" state=present
  when: freepbx_version == 14

- name: Add PHP5.6 repository
  apt_repository:
    repo: "deb https://packages.sury.org/php/ {{ ansible_distribution_release }} main"
    filename: "deb.sury.org"
    state: present
    update_cache: Yes
  when: freepbx_version == 14

- name: Set PHP version
  set_fact:
    php_version: "5.6"
  when: freepbx_version == 14

- name: Set PHP version
  set_fact:
    php_version: "7.3"
  when: freepbx_version != 14

- name: Install PHP{{ php_version }} packages
  apt:
    name:
      - php{{ php_version }}
      - php{{ php_version }}-curl
      - php{{ php_version }}-cli
      - php{{ php_version }}-pdo
      - php{{ php_version }}-mysql
      - php{{ php_version }}-odbc
      - php-pear
      - php{{ php_version }}-gd
      - php{{ php_version }}-mbstring
      - php{{ php_version }}-intl
      - php{{ php_version }}-xml
      - libapache2-mod-php{{ php_version }}
