---
- name: Install required packages 
  apt:
    name:
      - curl
      - policykit-1
      - libmariadbclient-dev
      - apt-transport-https
      - net-tools
      - build-essential 
      - mariadb-client 
      - bison 
      - flex 
      - apache2 
      - libapache2-mod-php
      - php 
      - php-curl 
      - php-cli 
      - php-pdo 
      - php-mysql 
      - php-odbc
      - php-pear 
      - php-gd 
      - php-mbstring 
      - php-intl 
      - curl 
      - sox 
      - libncurses5-dev 
      - libssl-dev 
      - lame
      - ffmpeg
      - mpg123 
      - libxml2-dev 
      - libnewt-dev 
      - sqlite3 
      - libsqlite3-dev 
      - pkg-config 
      - automake 
      - libtool 
      - autoconf 
      - git 
      - unixodbc-dev 
      - uuid 
      - uuid-dev 
      - libasound2-dev 
      - libogg-dev 
      - libvorbis-dev 
      - libicu-dev 
      - libcurl4-openssl-dev 
      - libical-dev 
      - libneon27-dev 
      - libsrtp2-dev 
      - libspandsp-dev 
      - sudo 
      - subversion 
      - libtool-bin 
      - python-dev 
      - unixodbc 
      - dirmngr 
      - sendmail-bin 
      - sendmail 
      - cmake 
      - cron 
      - sudo 
      - wget 
      - curl 
      - libmariadb-dev
      - python-mysqldb
      - libedit-dev
    state: present

- name: Install MariaDB Server
  apt:
    name:
      - mariadb-server
  when: mysql_install