- name: Remove existing install source dir
  file: "path={{ asterisk_install_srcdir }} state=absent"

- name: Create install source dir
  file: "path={{ asterisk_install_srcdir }} state=directory"

- name: Download and extract Asterisk source
  unarchive: "src={{ asterisk_install_url }} dest={{ asterisk_install_srcdir }} remote_src=yes extra_opts=--strip-components=1"

- name: Get sound sources
  command: "contrib/scripts/get_mp3_source.sh chdir={{ asterisk_install_srcdir }}"

- name: Build Asterisk | configure
  command: "{{ item }} chdir={{ asterisk_install_srcdir }}"
  with_items:
    - ./configure {{ asterisk_build_confopts | join(' ')}}

- name: Build Asterisk | configure build opts
  command: "{{ item }} chdir={{ asterisk_install_srcdir }}"
  with_items:
    - make menuselect.makeopts
    - menuselect/menuselect --enable {{ asterisk_build_modules | join(' --enable ')}}

- name: Build Asterisk | build and install
  command: "{{ item }} chdir={{ asterisk_install_srcdir }}"
  with_items:
    - make -j2
    - make uninstall-all
    - make install
    - make config
    - make samples
    - ldconfig

- name: Disable asterisk start at boot
  service:
    name: asterisk
    enabled: no
